
version: '3.8'

services:
  text_reader:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile_read
    volumes:
      - .:/app
    entrypoint: ["python", "/app/scripts/read_image.py"]

  rotate:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile_rotate
    volumes:
      - .:/app
    entrypoint: ["python", "/app/scripts/rotate_image.py"]

